# Port Configuration
server:
  port: 9091

# Datasource properties
spring:
  application:
    name: task-scheduler
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db?createDatabaseIfNotExist=true
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  redis:
    host: localhost
    port: 6379

#JWT ARGS
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000

logging:
  level:
#    org.springframework.data.*.*: trace
#    org.springframework.cache.*: trace
    org.springframework.security: DEBUG
#      hibernate:
#        SQL: DEBUG
#        orm:
#          jdbc:
#            bind: trace
#        type:
#          descriptor:
#            sql: trace

